language: android
jdk: oraclejdk8

android:
  components:
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository

script:
  - ./gradlew build jacocoTestCoverage generateRelease updateBintrayConfig

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r neatle/build/reports/jacoco/jacocoReleaseTestCoverage/jacocoReleaseTestCoverage.xml

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: lX3j0DNG126YSNG9HcKUZcCMVkLDXpugBCd57eTWcG4JFH+G3WGOiXXSCtQtzN9bUsSzKSRc9RgLNAowurj5ZH7QW5vuDpgGS02LTtiF31YA+j42cq39cZUcQOB/BCNqHXy5HCm1RdB4hPSdlnPIOnispY8tsGlPFCChdyRVE7cmGGAwHcOHwG8hVRnNacruLAaCbEq/TV5J7TdtHU6Mr/kr+wrTl2YKdSe7+2jcF/v9epr+x0fdTnA8xgagtcQUdkfhpVKXF3BfeWYsdazjDI735Fw8zD3X6jP/wLkFm1M27qZ7VC3egE4TR0DwAu3T6Rpy1aS28MfkEe2UvDWFMHlEwO3MiK2+9DiJCW91o9jsd3YV2eNHU2ubYj83PifqDt/3PZmarY/DGn7yKhOWQRjARal5xgffvgHPq0NLHo8mfZRvph3tm1pltBdIbk8lbv1z4RoMWOPTlqYWnnIHEyWtbuCea93x95w6+UIfyPJN/t5b3KBBZrU0KXuA83319aLk89JxKxf1Jy0uIOz3EfUQWwkaPWDk8RBgxjhQgOqA/qAdvvhJ7v8RzIwto7L+Kh3bJrXfhvpI0HjpwlE3yHGasZJz635uUXMbXE8pm8vRei0i+hEwJAAjNbEFYfamHIB3NhVjegZBAu2+3vVXMfLYL8dPoRVTWnXMgLb7UkM=
    file_glob: true
    file: neatle/build/outputs/aar/neatle-*-release.aar
    on:
      repo: inovait/neatle
      tags: true
  - provider: bintray
    skip_cleanup: true
    user: mihakinova
    key:
      secure: oMS/IkhXSnFgV4YS+r/TPL7DBDKeGPoEII+ln/ZLFAP53M92waz63LaaAWxiY3h979FDB4oZK6ZQDxna1aOQFGExtolhee/9bQHj//btDOE1QN1eL2dWB66zSTNjM82jte/0pHGy6mMuhKnH7S9OLCHKDv7xdjSsVjvsx4BWHT06WVv/HtcUVYgcspls2EGr1RAYvTEbUyJ293kYlOEIiPd4N1Abqhq/ktPG/3zkgON9kFSojpmOvnpUSHRlOa5diP9AqLzv9c13BLlL7l06a3e5J7xiYcTUmDOA6I96Ls+uro1apr49/qEqKHVTIQuf/4QAqPHQDANMPTlx9kcQCau5QdbpPxfJqUAwcFWM6cn/6fUoMYqwjX5rICAqdoN8RXpipva+PJKvlRjbcYEyG3A289Q2HWwR5KrHA4AyJ1+fMYykpOD0594eYkVmPRwwYIZGmOV5lRihRl3nUQ8SFea+9PUP2ZJOoESnO5SwrYGo4r9NeZtSa1udJa9ikFTlAqGkWwoQHEfAqDorkm3P75QtCtRPIzjrOCcdDIwRkpPs0f2oAP9jQYkRoIJuQ73m+wYCjazeEw5g6yPiMJloiiO5c92Z3CSArMPd2oAbfo6krl4tbowiYm5/czBydyDR56vkc33NlGMBCyne9h33xkM7lYgOMnGsV2V93dmFE04=
    file: neatle/bintray.json
    on:
      repo: inovait/neatle
      tags: true

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
